label {
  monitor =
  text = $TIME
  font_size = 100
  position = 0, 120
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33 # size of input dots
    dots_spacing = 0.15 # space between input dots
    dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
    outer_color = rgb(151515)
    inner_color = rgb(FFFFFF)
    font_color = rgb(000000)
    fade_on_empty = false
}
